### ISSUE TITLE
Error with wheels during install

### ISSUE THREAD

**Issue by jnovic** [david-cortes/cmfrec#10]
using python -m pip install --user cmfrec as my command  with pip 20.1  I was doing this on a windows machine and tried to install any dependencies that I thought were missing.  Still received the error.  

Hope this is useful.  If there was something I am missing about this, please let me know.
  
Error Message below:

Building wheel for cmfrec (PEP 517) ... error
  ERROR: Command errored out with exit status 120:
   command: 'C:\ProgramData\Anaconda3\python.exe' 'C:\Users\PANDA02-User\AppData\Roaming\Python\Python37\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\PANDA0~1\AppData\Local\Temp\tmpbjtjyp_p'
       cwd: C:\Users\PANDA0~1\AppData\Local\Temp\pip-install-_4effq2o\cmfrec
  Complete output (77 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\cmfrec
  copying cmfrec\__init__.py -> build\lib.win-amd64-3.7\cmfrec
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  C:\Users\PANDA0~1\AppData\Local\Temp\pip-build-env-6e0raycy\overlay\Lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  C:\Users\PANDA0~1\AppData\Local\Temp\pip-build-env-6e0raycy\overlay\Lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  C:\Users\PANDA0~1\AppData\Local\Temp\pip-build-env-6e0raycy\overlay\Lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
  Traceback (most recent call last):
    File "C:\Users\PANDA02-User\AppData\Roaming\Python\Python37\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "C:\Users\PANDA02-User\AppData\Roaming\Python\Python37\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\PANDA02-User\AppData\Roaming\Python\Python37\site-packages\pip\_vendor\pep517\_in_process.py", line 205, in build_wheel
      metadata_directory)
    File "C:\Users\PANDA0~1\AppData\Local\Temp\pip-build-env-6e0raycy\overlay\Lib\site-packages\setuptools\build_meta.py", line 213, in build_wheel
      wheel_directory, config_settings)
    File "C:\Users\PANDA0~1\AppData\Local\Temp\pip-build-env-6e0raycy\overlay\Lib\site-packages\setuptools\build_meta.py", line 198, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\PANDA0~1\AppData\Local\Temp\pip-build-env-6e0raycy\overlay\Lib\site-packages\setuptools\build_meta.py", line 250, in run_setup
      self).run_setup(setup_script=setup_script)
    File "C:\Users\PANDA0~1\AppData\Local\Temp\pip-build-env-6e0raycy\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 63, in <module>
      define_macros = [("_FOR_PYTHON", None)]
    File "C:\Users\PANDA0~1\AppData\Local\Temp\pip-build-env-6e0raycy\overlay\Lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\PANDA0~1\AppData\Local\Temp\pip-build-env-6e0raycy\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\PANDA0~1\AppData\Local\Temp\pip-build-env-6e0raycy\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "setup.py", line 31, in build_extensions
      build_ext_with_blas.build_extensions(self)
    File "C:\Users\PANDA0~1\AppData\Local\Temp\pip-build-env-6e0raycy\overlay\Lib\site-packages\findblas\distutils.py", line 28, in build_extensions
      raise ValueError(txt)
  ValueError: Found MKL library at:
  C:/ProgramData/Anaconda3/Library/bin\mkl_rt.dll
  However, it is missing .lib files - please install them with 'pip install mkl-devel'.
  Exception ignored in: <_io.TextIOWrapper mode='w' encoding='cp1252'>
  ValueError: underlying buffer has been detached
  ----------------------------------------
  ERROR: Failed building wheel for cmfrec
Failed to build cmfrec
ERROR: Could not build wheels for cmfrec which use PEP 517 and cannot be installed directly

(base) C:\Users\PANDA02-User>

**Comment by david-cortes** [comment]
This is the key issue in the message:
```
However, it is missing .lib files - please install them with 'pip install mkl-devel'.
```

You need to install either MKL or OpenBLAS. Also it seems either your NumPy or SciPy are built without them, which will make them very slow on linear algebra.

**Comment by jnovic** [comment]
I have installed MKL and a version of numpy + mkl 
I'm still getting the error message, I've been trying to figure out if there is something that I'm missing that I didn't realize.

I'm using Python 3.7

ERROR: Failed building wheel for cmfrec
Failed to build cmfrec
ERROR: Could not build wheels for cmfrec which use PEP 517 and cannot be installed directly

 
The full error message is below:
  ERROR: Command errored out with exit status 120:
   command: 'C:\ProgramData\Anaconda3\python.exe' 'C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\\Local\Temp\tmp2w8ss1bi'
       cwd: C:\Users\SENAdmin\AppData\Local\Temp\pip-install-0ibvsimh\cmfrec
  Complete output (75 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\cmfrec
  copying cmfrec\__init__.py -> build\lib.win-amd64-3.7\cmfrec
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  C:\Local\Temp\pip-build-env-v0k6r8p9\overlay\Lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  C:Local\Temp\pip-build-env-v0k6r8p9\overlay\Lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  C:\Local\Temp\pip-build-env-v0k6r8p9\overlay\Lib\site-packages\numpy\distutils\system_info.py:1896: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
  Traceback (most recent call last):
    File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 257, in <module>
      main()
    File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 182, in build_wheel
      metadata_directory)
    File "\Local\Temp\pip-build-env-v0k6r8p9\overlay\Lib\site-packages\setuptools\build_meta.py", line 213, in build_wheel
      wheel_directory, config_settings)
    File "\Local\Temp\pip-build-env-v0k6r8p9\overlay\Lib\site-packages\setuptools\build_meta.py", line 198, in _build_with_temp_dir
      self.run_setup()
    File "\Temp\pip-build-env-v0k6r8p9\overlay\Lib\site-packages\setuptools\build_meta.py", line 250, in run_setup
      self).run_setup(setup_script=setup_script)
    File "\Local\Temp\pip-build-env-v0k6r8p9\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 63, in <module>
      define_macros = [("_FOR_PYTHON", None)]
    File "Local\Temp\pip-build-env-v0k6r8p9\overlay\Lib\site-packages\setuptools\__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "C:\ProgramData\Anaconda3\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "\Temp\pip-build-env-v0k6r8p9\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\ProgramData\Anaconda3\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\ProgramData\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\ProgramData\Anaconda3\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "Local\Temp\pip-build-env-v0k6r8p9\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "C:\ProgramData\Anaconda3\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "setup.py", line 31, in build_extensions
      build_ext_with_blas.build_extensions(self)
    File "\Local\Temp\pip-build-env-v0k6r8p9\overlay\Lib\site-packages\findblas\distutils.py", line 34, in build_extensions
      print("Installation: Using BLAS library found in:\n" + os.path.join(blas_path, blas_file) + "\n\n")
  ValueError: underlying buffer has been detached
  Exception ignored in: <_io.TextIOWrapper mode='w' encoding='cp1252'>
  ValueError: underlying buffer has been detached
  ----------------------------------------
  ERROR: Failed building wheel for cmfrec
Failed to build cmfrec
ERROR: Could not build wheels for cmfrec which use PEP 517 and cannot be installed directly

**Comment by david-cortes** [comment]
Hmm, that's a different error. Could you try cloning/downloading the repository and running
```
python setup.py build_ext --inplace --force
```
or
```
python setup.py install
```

**Comment by jnovic** [comment]
Hi

this is the error message that came up when I tried that:

  File "setup.py", line 7, in <module>
    from findblas.distutils import build_ext_with_blas
ModuleNotFoundError: No module named 'findblas'

**Comment by david-cortes** [comment]
That error means it's missing package `findblas` (`pip install findblas`). Are you trying to install it in a different environment? Because the first error message was from `findblas` so you had to have it installed already.

Also I recall there was an issue with numpy some time ago that used to throw the 2nd error message in some situations.

**Comment by david-cortes** [comment]
Tried a pip install on a fresh windows anaconda installation and got this same error. I think it's an issue with `setuptools`, and I'm not sure what to do about it. It installs fine if compiled from source however (`python setup.py install`).

**Comment by jnovic** [comment]
Thank you for all your help.  I was able to get it installed.
