### ISSUE TITLE
Errors during install on Windows

### ISSUE THREAD

**Issue by tangoed2whiskey** [david-cortes/cmfrec#13]
Hi, I'm having trouble installing the new version of cmfrec on Windows (was enjoying using a previous version last year):  I've attempted to use `pip install cmfrec` (error message 1 below); `pip install git+https://www.github.com/david-cortes/cmfrec.git` (also error message 1); cloning this repo and then running `python setup.py install` (error message 2 below); and cloning this repo and then running `python .\setup.py install --prefix=C:\\Users\\me\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages`, which asks if a dll is a BLAS library: answering yes results in error message 3.

This is a pretty fresh windows install, but has `numpy, scipy, findblas` installed.  Visual Studio 2019 is also installed, which claimed to come with Visual Studio Build Tools.  Using python 3.8.5, pip 20.1.1.  Any help as to why the install isn't working would be great!

Error message 1
```
Collecting cmfrec
  Using cached cmfrec-1.0.6.tar.gz (151 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: cython in c:\users\thoma\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from cmfrec) (0.29.21)
Requirement already satisfied: findblas in c:\users\thoma\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from cmfrec) (0.1.15)
Requirement already satisfied: numpy>=1.17 in c:\users\thoma\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from cmfrec) (1.19.1)
Requirement already satisfied: pandas>=0.25.0 in c:\users\thoma\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from cmfrec) (1.0.5)
Requirement already satisfied: pytz>=2017.2 in c:\users\thoma\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from pandas>=0.25.0->cmfrec) (2020.1)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\thoma\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from pandas>=0.25.0->cmfrec) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\users\thoma\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from python-dateutil>=2.6.1->pandas>=0.25.0->cmfrec) (1.15.0)
Building wheels for collected packages: cmfrec
  Building wheel for cmfrec (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\thoma\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' 'C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\thoma\AppData\Local\Temp\tmp5n_zv03y'
       cwd: C:\Users\thoma\AppData\Local\Temp\pip-install-gkukoip4\cmfrec
  Complete output (77 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\cmfrec
  copying cmfrec\__init__.py -> build\lib.win-amd64-3.8\cmfrec
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\numpy\distutils\system_info.py:1914: UserWarning:
      Optimized (vendor) Blas libraries are not found.
      Falls back to netlib Blas library which has worse performance.
      A better performance should be easily gained by switching
      Blas library.
    if self._calc_info(blas):
  C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\numpy\distutils\system_info.py:1914: UserWarning:
      Blas (http://www.netlib.org/blas/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [blas]) or by setting
      the BLAS environment variable.
    if self._calc_info(blas):
  C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\numpy\distutils\system_info.py:1914: UserWarning:
      Blas (http://www.netlib.org/blas/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [blas_src]) or by setting
      the BLAS_SRC environment variable.
    if self._calc_info(blas):
  C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\findblas\__init__.py:489: UserWarning: No BLAS library found - taking NumPy's linalg's file as library.
    warnings.warn("No BLAS library found - taking NumPy's linalg's file as library.")
  Traceback (most recent call last):
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
      main()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\setuptools\build_meta.py", line 229, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\setuptools\build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\setuptools\build_meta.py", line 266, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 33, in <module>
      setup(
    File "C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\setuptools\__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 340, in run
      self.build_extensions()
    File "setup.py", line 31, in build_extensions
      build_ext_with_blas.build_extensions(self)
    File "C:\Users\thoma\AppData\Local\Temp\pip-build-env-39h4rkac\overlay\Lib\site-packages\findblas\distutils.py", line 32, in build_extensions
      raise ValueError(txt)
  ValueError: Found BLAS library at:
  C:/Users/thoma/AppData/Local/Temp/pip-build-env-39h4rkac/overlay/Lib/site-packages/numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
  But .lib files are missing! Please reinstall it (e.g. 'pip install mkl-devel').
  ----------------------------------------
  ERROR: Failed building wheel for cmfrec
Failed to build cmfrec
ERROR: Could not build wheels for cmfrec which use PEP 517 and cannot be installed directly
```

Error message 2
```
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-5564.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\Lib\site-packages\

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.
```

Error message 3
```
running install
Checking .pth file support in C:\\Users\\thoma\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\Lib\site-packages\
C:\Users\thoma\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\pythonw.exe -E -c pass
TEST FAILED: C:\\Users\\thoma\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\Lib\site-packages\ does NOT support .pth files
bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\\Users\\thoma\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\site-packages\Lib\site-packages\

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
running bdist_egg
running egg_info
writing cmfrec.egg-info\PKG-INFO
writing dependency_links to cmfrec.egg-info\dependency_links.txt
writing requirements to cmfrec.egg-info\requires.txt
writing top-level names to cmfrec.egg-info\top_level.txt
reading manifest file 'cmfrec.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '.gitignore'
warning: no previously-included files found matching '.gitattributes'
warning: no previously-included files found matching 'example\*'
warning: no previously-included files found matching 'cmfrec\*.c'
warning: no previously-included files found matching 'docs\*'
no previously-included directories found matching 'docs\*'
writing manifest file 'cmfrec.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
C:\Users\thoma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\distutils\system_info.py:1914: UserWarning: 
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
C:\Users\thoma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\distutils\system_info.py:1914: UserWarning: 
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  if self._calc_info(blas):
C:\Users\thoma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\distutils\system_info.py:1914: UserWarning:
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  if self._calc_info(blas):
Found file with name matching 'blas'
/Users/thoma/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/scipy/.libslibopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
Is this a BLAS library? [y/n]: y
Traceback (most recent call last):
  File ".\setup.py", line 33, in <module>
    setup(
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\bdist_egg.py", line 173, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\bdist_egg.py", line 159, in call_command
    self.run_command(cmdname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Users\thoma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1520.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File ".\setup.py", line 31, in build_extensions
    build_ext_with_blas.build_extensions(self)
  File "C:\Users\thoma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\findblas\distutils.py", line 32, in build_extensions
    raise ValueError(txt)
ValueError: Found BLAS library at:
/Users/thoma/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/scipy/.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
But .lib files are missing! Please reinstall it (e.g. 'pip install mkl-devel').
```

**Comment by david-cortes** [comment]
Try the suggestion from the error message: pip install mkl-devel

**Comment by tangoed2whiskey** [comment]
Tried and made no difference I'm afraid

**Comment by david-cortes** [comment]
Please post the outputs from the following:
(in  a console)
```
pip show -f mkl-devel
```

(in python, having package `findblas` installed, also available from `pip` if you don't already have it)
```python
import findblas
print(findblas.find_blas())
```

**Comment by tangoed2whiskey** [comment]
Thanks for looking into this:  outputs as follows

```
PS C:\Users\thoma\Documents\Git\cmfrec> pip show -f mkl-devel
Name: mkl-devel
Version: 2018.0.3
Summary: Math library for Intel and compatible processors     
Home-page: http://software.intel.com/en-us/articles/intel-mkl/
Author: Intel Corporation
Author-email: scripting@intel.com
License: Proprietary - Intel
Location: c:\users\thoma\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages
Requires: mkl-include, mkl
Required-by:
Files:
  mkl_devel-2018.0.3.dist-info\DESCRIPTION.rst
  mkl_devel-2018.0.3.dist-info\INSTALLER
  mkl_devel-2018.0.3.dist-info\LICENSE.txt
  mkl_devel-2018.0.3.dist-info\METADATA
  mkl_devel-2018.0.3.dist-info\RECORD
  mkl_devel-2018.0.3.dist-info\WHEEL
  mkl_devel-2018.0.3.dist-info\metadata.json
  mkl_devel-2018.0.3.dist-info\top_level.txt
```
and
```python
>>> import findblas
>>> print(findblas.find_blas())
C:\Users\thoma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\distutils\system_info.py:1914: UserWarning: 
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
C:\Users\thoma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\distutils\system_info.py:1914: UserWarning: 
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  if self._calc_info(blas):
C:\Users\thoma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\distutils\system_info.py:1914: UserWarning:
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  if self._calc_info(blas):
Found file with name matching 'blas'
/Users/thoma/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/scipy/.libslibopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
Is this a BLAS library? [y/n]:
```

The question at the end there is the same one found during the install process: answering yes returns
```python
('/Users/thoma/AppData/Local/Packages/PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0/LocalCache/local-packages/Python38/site-packages/scipy/.libs', 'libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll', None, None, ['UNKNWON_BLAS', 'UNKNWON_BLAS'])
```
[sic]

**Comment by david-cortes** [comment]
Hmm, that's very weird. It looks like you somehow have your Python libraries split into two different paths, and I'm guessing you might have 2 different python installs there.

For some reason, `findblas` doesn't find the `mkl` which should be under
```
c:\users\thoma\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages
```

The permission denied error I guess you got from the `setup.py` script, and for that you need to run the console/terminal as administrator.

Maybe try setting the `PYTHONPATH` environment variable to the one in `AppData` instead.

Otherwise, you can try the following:
* Edit the `requirements.txt` adding a line `mkl-devel` at the end, then run `python setup.py sdist` and then `pip install dist/cmfrec_<something_else_look_at_the_generated_file>`.
* Set both `PATH` and `PYTHONPATH` to point to your install in `AppData` (those are environment variables).
* Edit the `setup.py` file, changing `build_ext_with_blas` to `build_ext` from `Cython.Distutils`, manually adding linkage to the `mkl_rt.lib` file (the location can be found with `pip show -f mkl`) - you can check the package `findblas` (file `distutils.py`) for how to do this for visual studio.

**Comment by david-cortes** [comment]
May I ask also how did you install python like that? It's the first time I'm seeing such structure - usually the packages should be under something like `$PATH\Lib\site-packages` (in windows) or `$PATH/lib/python3.7/site-packages` (in linux), but you have them under `$PATH\localcache\local-packages\python38\site-packages`.

**Comment by david-cortes** [comment]
I've pushed an update to `findblas`, please update to the latest version (`pip install findblas==0.1.16`) and try again the pip install and the setup.py install. Please post again what you get from:
```python
import findblas
findblas.find_blas()
```

**Comment by tangoed2whiskey** [comment]
Thanks for your help!  I now get

```python
>>> import findblas
>>> findblas.find_blas()
C:\Users\thoma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\distutils\system_info.py:1914: UserWarning: 
    Optimized (vendor) Blas libraries are not found.
    Falls back to netlib Blas library which has worse performance.
    A better performance should be easily gained by switching
    Blas library.
  if self._calc_info(blas):
C:\Users\thoma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\distutils\system_info.py:1914: UserWarning:
    Blas (http://www.netlib.org/blas/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [blas]) or by setting
    the BLAS environment variable.
  if self._calc_info(blas):
C:\Users\thoma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\distutils\system_info.py:1914: UserWarning:
    Blas (http://www.netlib.org/blas/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [blas_src]) or by setting
    the BLAS_SRC environment variable.
  if self._calc_info(blas):
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
('c:/users/thoma/appdata/local/packages/pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0/localcache/local-packages/python38/site-packages/../../Library/lib', 'mkl_rt.lib', 'c:/users/thoma/appdata/local/packages/pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0/localcache/local-packages/python38/site-packages/../../Library/include', 'mkl.h', ['HAS_MKL'])
```
which looks better, and running `python setup.py install` with prefix specified appears to correctly install cmfrec.

However, I then get
```python
>>> import cmfrec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\thoma\Documents\Git\cmfrec\cmfrec\__init__.py", line 1, in <module>
    from . import wrapper_double, wrapper_float
ImportError: cannot import name 'wrapper_double' from partially initialized module 'cmfrec' (most likely due to a circular import) (C:\Users\thoma\Documents\Git\cmfrec\cmfrec\__init__.py)
```
so it hasn't fully installed properly ...

**Comment by david-cortes** [comment]
Do you get the same circular import error if you try instead:
```
python setup.py build_ext --inplace --force
```
And then try to import it from the same directory where the `setup.py` is located?

**Comment by tangoed2whiskey** [comment]
Different error when doing that!

```python
>>> import cmfrec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\thoma\Documents\Git\cmfrec\cmfrec\__init__.py", line 1, in <module>
    from . import wrapper_double, wrapper_float
ImportError: DLL load failed while importing wrapper_double: The specified module could not be found.
```

**Comment by david-cortes** [comment]
If you look at the folder `<where_you_cloned>/cmfrec`, do you see some files ending in `.pyd` in addition to the `.py`/`.pyx`/`.pxi` ones? Did `python setup.py build_ext --inplace --force` throw you any errors?

If the files are there, then I don't know - looks like for some reason it cannot load the dll files from the folder where you have them. Perhaps some issue with permissions. You could try installing python from conda/intel/visual studio or other.

**Comment by tangoed2whiskey** [comment]
Yes, I can see some .pyd files generated when I ran `python setup.py build_ext --inplace --force`.  That did not throw any errors.

```
PS C:\Users\thoma\Documents\Git\cmfrec\cmfrec> ls


    Directory: C:\Users\thoma\Documents\Git\cmfrec\cmfrec


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        17/08/2020     08:44                __pycache__
-a----        17/08/2020     12:08        2728983 cfuns_double.c
-a----        14/08/2020     10:46             98 cfuns_double.pyx
-a----        17/08/2020     12:09        2727068 cfuns_float.c
-a----        14/08/2020     10:46             96 cfuns_float.pyx
-a----        17/08/2020     12:09         737792 wrapper_double.cp38-win_amd64.pyd
-a----        17/08/2020     12:09         741376 wrapper_float.cp38-win_amd64.pyd
-a----        14/08/2020     10:46         102694 wrapper_untyped.pxi
-a----        14/08/2020     10:46         272314 __init__.py
```

**Comment by tangoed2whiskey** [comment]
I have also just tried to install on my WSL system, again getting a lot of errors: in particular, when running `sudo python3 setup.py install` (sudo to avoid permissions issues), the install cannot find `findblas` and `cython` that I just pip installed on that system.  However, when I do `sudo pip3 install findblas cython` the cmfrec setup can now find those libraries.  It installs without errors, and then throws
```python
>>> import cmfrec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/thoma/Documents/Git/cmfrec/cmfrec/__init__.py", line 1, in <module>
    from . import wrapper_double, wrapper_float
ImportError: cannot import name 'wrapper_double' from partially initialized module 'cmfrec' (most likely due to a circular import) (/mnt/c/Users/thoma/Documents/Git/cmfrec/cmfrec/__init__.py)
```
again.

I'm going to go back to the `tensorflow` branch for now, which installs perfectly for me.

**Comment by david-cortes** [comment]
I think part of the issue is mixing sudo with user installs of libraries. If you are using WSL, the pip install (`pip install cmfrec`) should work fine (it would use the same openblas from numpy that you have there) **as user** as long as your numpy is also installed as user, but it will be slow as MKL/OpenBLAS work poorly on WSL.

**Comment by PWSchaefer** [comment]
I'm also getting very similar errors when installing cmfrec. Have scoured this repo and tried every solution with no luck. The only version of cmfrec that I am able to successfully install and setup is cmfrec-0.5.2.3.

**Comment by david-cortes** [comment]
> I'm also getting very similar errors when installing cmfrec. Have scoured this repo and tried every solution with no luck. The only version of cmfrec that I am able to successfully install and setup is cmfrec-0.5.2.3.

Could you copy and paste the full error message here? Please use three backticks (``` ` ```) before and after to format it as code.

Would also be helpful to know how:
* How did you install python and numpy/scipy?
* Do you have multiple parallel installations?
* Is it installed as a system program (e.g. under `C:\Program Files`) or as a user program (e.g. under `C:\Users\You`)?
* Do you get errors from both `pip install cmfrec` and `pip install --no-pep-517 cmfrec`?
* Do you get errors if installing without pip? (`python setup.py install`)

**Comment by david-cortes** [comment]
@PWSchaefer Could you try this too?
```pip install git+https://github.com/david-cortes/cmfrec.git@scipy_blas```

**Comment by PWSchaefer** [comment]
> Would also be helpful to know how:
> 
> * How did you install python and numpy/scipy?
> * Do you have multiple parallel installations?
> * Is it installed as a system program (e.g. under `C:\Program Files`) or as a user program (e.g. under `C:\Users\You`)?
> * Do you get errors from both `pip install cmfrec` and `pip install --no-pep-517 cmfrec`?
> * Do you get errors if installing without pip? (`python setup.py install`)

After troubleshooting a bit more and wanting to ensure that I didn't have any strange parallel installations, I restored my copy of windows (long overdue), reinstalled Anaconda, and the issue was resolved. Thanks for your help!
