### ISSUE TITLE
Mac installation w/ Homebrew Python

### ISSUE THREAD

**Issue by ankane** [david-cortes/cmfrec#20]
Hi, just wanted to report the C library finds BLAS that ships w/ Mac, but the Python package doesn't.

CMake output

```text
-- Found BLAS: /Applications/Xcode_12.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Accelerate.framework 
```

Python output

```text
Building wheels for collected packages: cmfrec
  Building wheel for cmfrec (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python@3.9/bin/python3.9 /usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/tmp8xl02vuw
       cwd: /private/var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/pip-install-mmdobivr/cmfrec
  Complete output (64 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.15-x86_64-3.9
  creating build/lib.macosx-10.15-x86_64-3.9/cmfrec
  copying cmfrec/__init__.py -> build/lib.macosx-10.15-x86_64-3.9/cmfrec
  running build_ext
  /var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/tmpbgte3umb/source.c:1:10: fatal error: 'cblas.h' file not found
  #include <cblas.h>
           ^~~~~~~~~
  1 error generated.
  /var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/tmpyofnvb9v/source.c:1:10: fatal error: 'cblas.h' file not found
  #include <cblas.h>
           ^~~~~~~~~
  1 error generated.
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/pip-build-env-yae_2b7_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/pip-build-env-yae_2b7_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/pip-build-env-yae_2b7_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/pip-build-env-yae_2b7_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 94, in <module>
      setup(
    File "/private/var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/pip-build-env-yae_2b7_/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/pip-build-env-yae_2b7_/overlay/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/pip-build-env-yae_2b7_/overlay/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "setup.py", line 64, in build_extensions
      build_ext_with_blas.build_extensions(self)
    File "/private/var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/pip-build-env-yae_2b7_/overlay/lib/python3.9/site-packages/findblas/distutils.py", line 22, in build_extensions
      blas_path, blas_file, incl_path, incl_file, flags = findblas.find_blas()
    File "/private/var/folders/2t/6lmb55md2kj8pspr5nsfv7rw0000gn/T/pip-build-env-yae_2b7_/overlay/lib/python3.9/site-packages/findblas/__init__.py", line 438, in find_blas
      flags_found += found_syms[1]
  TypeError: 'NoneType' object is not iterable
  ----------------------------------------
  ERROR: Failed building wheel for cmfrec
Failed to build cmfrec
ERROR: Could not build wheels for cmfrec which use PEP 517 and cannot be installed directly
```

I was able to get the Python package working w/ OpenBLAS, but it'd be nice if it found the built-in one like CMake.

```sh
brew install openblas
export USE_OPENBLAS=1
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openblas/lib
pip3 install cmfrec
```

**Comment by david-cortes** [comment]
Thanks for the bug report. That’s an interesting issue and didn’t know that macOS shipped its own blas library.

Could you check what’s the output from package [findblas](https://www.github.com/david-cortes/findblas)? (`pip install findblas`)
```python
import findblas
findblas.find_blas()
```

**Comment by ankane** [comment]
Here's the output both locally and on GitHub Actions:

```text
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
WARNING: Package(s) not found: mkl
Traceback (most recent call last):
  File "/Users/runner/work/cmfrec_repro/cmfrec_repro/main.py", line 2, in <module>
    findblas.find_blas()
  File "/usr/local/lib/python3.9/site-packages/findblas/__init__.py", line 438, in find_blas
    flags_found += found_syms[1]
TypeError: 'NoneType' object is not iterable
```

https://github.com/ankane/cmfrec_repro/runs/1470735569?check_suite_focus=true

**Comment by david-cortes** [comment]
Thank you. I've pushed a small update to `findblas`. Could you check again what does it output with version `findblas==0.1.17` ?

**Comment by ankane** [comment]
Looks like that fixed it. Thanks! https://github.com/ankane/cmfrec_repro/runs/1470756707?check_suite_focus=true
